# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - finalworkapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
  buildDocker:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://dockerforfinalwork.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f9f71b5baf904f929f0f85261ad802ca }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8825e9b67d4848df8a228a6ad814cc13 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dockerforfinalwork.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f9f71b5baf904f929f0f85261ad802ca }}/api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: buildDocker
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'finalworkapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_105b5223840144779c8d3ef8791d9a1d }}
        images: 'dockerforfinalwork.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f9f71b5baf904f929f0f85261ad802ca }}/api:${{ github.sha }}'